import Head from 'next/head'
import Image from 'next/image'


export default function Home({ posts }) {

    // console.log(posts.slip.advice)
  return (
    <div data-theme="valentine">
      <Head>
        <title>Compliment for darling</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
            <div className='min-h-screen flex fle-col bg-base-300 justify-center items-center'>
                <div className="py-4  px-4 bg bg-base-200 rounded-[32px] rounded">
                <div className=" bg-base-300 max-w-2xl flex flex-col  justify-center items-center bg-opacity-80 bg-clip-padding   rounded-[16px] adwfasd">
                    {/*<h2 className="pt-10 text-2xl font-extrabold">Advice <span className="text-accent">#{posts.slip.id}</span></h2>*/}
                    <h2 className="p-16 text-3xl  font-bold">"{posts}"</h2>
                </div>
                </div>
            </div>
    </div>
  )
}
export async function getStaticProps() {
    const posts = await ((await fetch('https://8768zwfurd.execute-api.us-east-1.amazonaws.com/v1/compliments')).json())


    return {
        props: {
            posts
        }
    }
}